### ISSUE TITLE
Edit_Normals Modifier (specified/explicit) normals not supported.

### ISSUE THREAD

**Issue by Archangel35757** [paulvortex/MaxDpMd3Exporter#1]
Hello.  Your revised code does support unspecified normals associated with Smoothing Groups.  However, your code does not address specified/explicit normals associated with an Edit Normals modifier.  To add support for "Edit Normals" you must use the class MeshNormalSpec (see MeshNormalSpec.h file).

class MeshNormalSpec is an interface used to store user-specified normals (such as those created in the Edit Normals modifier).  The MeshNormalSpec contains three types of normals:

**Unspecified** - these are the usual normals that are computed from smoothing groups. All normals are unspecified by default.

**Specified** - these are normals that are intended for use by particular corners of particular faces, without regard to smoothing groups. For instance, you can create a box, apply Edit Normals, select a group of normals at a particular vertex, and click "Unify". Now those three faces are told to specifically use that one unified normal, and they ignore their smoothing groups at that vertex (which would normally tell them they should each have their own normal).

**Explicit** - these are normals that are set to particular values. For instance, if the user wants to use the Edit Normals Move or Rotate commands to set a normal to something other than its default value, it has to be made explicit, so it won't be recomputed based on the face normals. All explicit normals are also considered to be specified.

I would like your assistance in fixing the code so that Edit Normals modifier is supported.  Thank you!

**Comment by paulvortex** [comment]
Hello!

"SPECIFIED_NORMAL" code part is the right place to look at. However, the 
SPECIFIED_NORMAL flag itself considered unused in Max SDK so it is not supposed to be working at all. It should be fixed with some actual (the code which gets normal of vertex). 

Could you send me the test box file you have (and 3dmax version you created it with)? Mail is paul.vortex@gmail.com .

**Comment by paulvortex** [comment]
Hi Michael! Seems i got it fixed. Check out fresh commit and see mail.
