### ISSUE TITLE
Unable to export frames beyond "1" ( 2012 64bit +2014 64bit )

### ISSUE THREAD

**Issue by Doommarine23** [paulvortex/MaxDpMd3Exporter#2]
While my MD3 models export perfectly fine, it seems that no matter what I type into the "Frame Range" box it exports only the first (1) frame. I've attempted this on 2012 64bit and 2014 64bit with the same results.

I thought it might have been the bone animation I was using so I tried as a test by moving the polygons and vertices around on a few frames to see if that exported and it made no difference either.

I really appreciate the work put into this and I'm hoping you can help me figure out what is going on because I feel like its just me making a huge mistake and I just can't wrap my head around what could be happening. Thank you for listening.

**Comment by Archangel35757** [comment]
@Doommarine23, are you exporting a Quake3 player model? Or what?  How did you enter the range?  Like so:  0-100 or what?  Not to hi-jack your request for help from paulvortex here... I'm sure he'll help you look into it; but could I get you to try out another MD3 exporter that I've just compiled?  You can contact me at:  jkhub.org

**Comment by Doommarine23** [comment]
I must admit this is embarrassing. I attempted using 0-100 before and it did not work but it seems to now.  I appreciate you bringing it up, I don't think I would have tried it again if you didn't mention it.
I really do apologize for this Issue report, quite the egg on my face.

However @Archangel35757 I will try out your exporter, I'll contact you, hopefully I can be of some use.
